version: "3"

services:
 nodejs_server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodejs_server
    ports:
      - "9060:8080"
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules